# Generated by Django 6.1 on 2026-09-24 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mesa', models.CharField(max_length=10)),
                ('capacidad_min', models.IntegerField()),
                ('capacidad_max', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table_comment': 'Mobiliario físico y capacidad asignable para cada sector',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=15, unique=True)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin_estimada', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('comentario', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table_comment': 'Registro central de las reservas realizadas por los clientes',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('capacidad_total', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table_comment': 'Datos principales de cada local o sucursal',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table_comment': 'Roles de usuario en la plataforma (cliente, Administrador, Garzón)',
            },
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(max_length=100)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.mesa')),
            ],
            options={
                'db_table_comment': 'Excepciones de disponibilidad (puede ser por mantención, avería o eventos privados)',
            },
        ),
        migrations.CreateModel(
            name='ReservaMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.mesa')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reserva')),
            ],
            options={
                'db_table_comment': 'tabla intermedia para asociar una o múltiples mesas físicas a una reserva',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesas',
            field=models.ManyToManyField(related_name='reservas', through='reservations.ReservaMesa', to='reservations.mesa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.restaurante'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.restaurante')),
            ],
            options={
                'db_table_comment': 'ambientes disponibles dentro de cada restaurante (Terraza, inferior, VIP, etc.)',
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.sector'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.rol')),
            ],
            options={
                'db_table_comment': 'información de los clientes y personal del restaurante',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.usuario'),
        ),
        migrations.CreateModel(
            name='CambioReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_actual', models.CharField(max_length=20)),
                ('motivo_cambio', models.CharField(max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.usuario')),
            ],
            options={
                'db_table_comment': 'Historial de auditoría para cambios de estado en las reservas',
            },
        ),
        migrations.AddConstraint(
            model_name='reservamesa',
            constraint=models.UniqueConstraint(fields=('reserva', 'mesa'), name='unique_reserva_mesa'),
        ),
    ]
